"""empty message

Revision ID: ac5d09943ae4
Revises: 
Create Date: 2020-05-31 09:56:17.998488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5d09943ae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accountings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paidPrice', sa.Float(), nullable=True),
    sa.Column('totalPrice', sa.Float(), nullable=True),
    sa.Column('ticket', sa.Integer(), nullable=True),
    sa.Column('user_from', sa.Integer(), nullable=True),
    sa.Column('user_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('ticket', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_items',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('items_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['items_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_items')
    op.drop_table('items')
    op.drop_table('accountings')
    op.drop_table('users')
    op.drop_table('tickets')
    # ### end Alembic commands ###
